boshurik_telegram_bot:
    api:
        token: "%env(TELEGRAM_BOT_TOKEN)%"
    guard:
        default_target_route: user_profile  # redirect after login success
        guard_route: _telegram_login        # dafaults to path /_telegram/<a_secret_token>/login
        login_route: your_login_route       # optional, if login fails user will be redirected there
